### ISSUE TITLE
Hashview Agent on Windows

### ISSUE THREAD

**Issue by nicbrink** [hashview/hashview-agent#1]
This may not be the right place for this, but I was able to get the Hashview-agent to run on Windows with surprisingly little effort. 

Here are the directions I put together:

Install Intel CL Drivers:
https://software.intel.com/en-us/articles/opencl-drivers#latest_CPU_runtime
 
Install AMD Catalyst Drivers:
http://support.amd.com/en-us/kb-articles/Pages/latest-catalyst-windows-beta.aspx
 
Install HashCat:
https://hashcat.net/hashcat/
#Note: I installed it to d:\opt\hashcat
 
Test Hashcat:
hashcat64.exe -m 1000 -b
 
Install Git:
#Note this is for two reasons, one to pull the agent, but more importantly it comes with mingw64
#Use Option 3, Git and optional Unix tools from the windows command prompt
 
Download Hash-view Agent:
git clone https://github.com/hashview/hashview-agent.git
 
Download and install Ruby:
https://dl.bintray.com/oneclick/rubyinstaller/rubyinstaller-2.2.2-x64.exe 
#Note check the add ruby to the system path option
 
#Update the Certificate using this link - There is an issue with ruby and windows regarding SSL certificates, I had to manually update the cert to install gems
http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue
 
Install Bundler:
gem install bundler
 
#Change directory to hashview
bundle install
#Ignore the JSON error, or remove the JSON entry from the Gemfile since ruby has the JSON gem already
 
#Note: if git did not add its linux tools to the path, do so now
PATH=%path%;d:\opt\git\usr\bin\
 
Provision:
set RACK_ENV=production
rake provision_remote_agent
 
Edit the config file:
{
  "master_ip": "10.1.1.1",
  "port": "4567",
  "uuid": "26f8f90f-0776-44e3-85f5-27b74fd890eb",
  "hc_binary_path": "d:\\opt\\hashcat\\hashcat64.exe",
  "type": "slave"
}
 
Running:
set RACK_ENV=production
ruby agent.rb
 
 

I get this error the first time I run it, but it seems fine after that
```
D:/opt/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:155:in `parse': 757: unexpected token at '"#<Sinatra::Response:0x007f36e4d62de8>"' (JSON::ParserError)
        from D:/opt/Ruby22-x64/lib/ruby/2.2.0/json/common.rb:155:in `parse'
        from D:/opt/hashview/background_worker.rb:327:in `<top (required)>'
        from agent.rb:17:in `require_relative'
        from agent.rb:17:in `<main>'
agent has 2 CPUs
agent has 1 GPUs
agent max cracking speed (single NTLM hash):
  2595.1 MH/s (50.91ms)
HEARTBEETING
```

**Comment by i128** [comment]
Dude, thats freaking awesome! Good work!

**Comment by jjmoody** [comment]
I know this isn't a supported feature but due to difficulties finding OpenCL/AMD driver combinations that deliver hashing speeds anywhere close to the advertised benchmark for RX580's on Ubuntu, I attempted to do this... when I use Hashcat on Windows my hashing speeds at about 3 times higher than Linux at the moment due to crappy drivers.

Anyway, it would be great if someone could build Windows support into the Agent too! I also get several errors, but in my case due to the Ruby version 2.2.2 being depreciated it will not start the Heartbeat... and hashview-agent is lifeless at the moment :) Will this be updated to use Ruby 2.4.4 like hashview anytime soon? Or does anyone have a tidbit of advice for getting this running in Windows at it stands?

**Comment by noobscode** [comment]
Jimoody: love the idea! I need this agent on windows as well. Got my 1080 founders and 1070 card in windows machines but the hashview must run on linux.

Ccammilleri: do we need to swap out ruby 2.2.2 for 2.4.2 /2.4.4 for both the installed version and the set version in the gemfile?

I tried running the install with ruby 2.4.4. Failed on the gem logger. Might be old and outdated or replced with another gem.
