### ISSUE TITLE
distributing don't work 

### ISSUE THREAD

**Issue by johamha** [hashview/hashview-agent#5]
I have a "cluster" of 4 maschines and everytime the Hashview Head will assign work to one of the remote agents I get following error on the agent

Normal Logout:
{"status"=>200, "type"=>"message", "msg"=>"OK"}
HEARTBEETING

{"status"=>200, "type"=>"message", "msg"=>"START", "task_id"=>"13"}
HEARTBEETING
you need to download Smart Wordlist = e3b0c4.....52b855         //shortened 
Downloading...
Unpacking....
Calculating checksum

Then the Error: 
`/opt/hashview-agent/background_worker.rb:364:in `block in sync_wordlists': undefined local variable or method `checksum' for main:Object (NameError)
        from /opt/hashview-agent/background_worker.rb:325:in `each'
        from /opt/hashview-agent/background_worker.rb:325:in `sync_wordlists'
        from /opt/hashview-agent/background_worker.rb:445:in `<top (required)>'
        from agent.rb:18:in `require_relative'
        from agent.rb:18:in `<main>'`

I synced rules and wordlists manualy but it didn't help. 
Hashview master Version: 0.7.1
Hashview-agent Verson: [latest commit](https://github.com/hashview/hashview-agent)

**Comment by i128** [comment]
Do you have any files currently under: 
hashivew-agent/control/wordlists/ with the .checksum extension?

**Comment by nicbrink** [comment]
I think this one is on me.  When I added the check for mac due to the "sha256sum" issue I think the attempt to open the file occured before the calculation of the checksum.  I changed the order and cleaned up the os checking a bit and did a pull request.

**Comment by johamha** [comment]
@i128 : No there are only 
.blank 
password
password.gz 
and the SmartWordlist.txt (which is size of 0)
